spring.application.name=universe-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info

spring.datasource.hikari.max-lifetime=270000
spring.datasource.hikari.idle-timeout=240000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikri.keepalive-time=120000